# -*- coding: utf-8 -*-
"""preprocessingskripsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13GaIHdhIJI_mhFPFGKoP6Pyzr2sD1rhs
"""

import numpy as np
import pandas as pd
from google.colab import drive


drive.mount('/content/drive')

df=pd.read_csv('/content/drive/My Drive/coba skripsi/semuaberita.csv')
df

"""**casefolding**"""

import re

def cfm(narasi):
  narasi = narasi.lower()
  narasi = re.sub(r'@\w+', ' ', narasi)
  narasi = re.sub(r'\b\w{1,3}\b', '', narasi)
  narasi = re.sub(r'[0-9]+', '', narasi)
  narasi = re.sub(r'\s+', ' ', narasi)
  narasi = re.sub(r'#\w+', ' ', narasi)
  narasi = re.sub(r'^\s+',"",narasi)
  narasi = re.sub(r'\W'," ",narasi)
  return narasi

df['narasi1'] = df['narasi'].apply(lambda x: cfm(x))
df

df = df.drop_duplicates()
del df['judul'], df['narasi'], df['tanggal']
df

df.to_csv('casefolding.csv', index=False)

"""**tokenizing**"""

import nltk
nltk.download('punkt')

# tokenization df["text"]
df["narasi2"]=df.apply(lambda row: nltk.word_tokenize(row["narasi1"]), axis=1)
df

df.to_csv('tokenizing.csv', index=False)

"""**stopword**"""

!pip install Sastrawi

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
 
factory = StopWordRemoverFactory()
stopwords = factory.get_stop_words()
def stopword(text):
  text = [w for w in text if not w in stopwords]
  text = " ".join(text)
  return text

df['swnarasi'] = df['narasi2'].apply(stopword)
df

df.to_csv('stopword.csv', index=False)

"""**Stemming**"""

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def Stemming(text):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()
  text = text.split()
  hasil = [stemmer.stem(token) for token in text]
  hasil = " ".join(hasil)
  return hasil

df['narasistem'] = df['swnarasi'].apply(Stemming)
df

df.to_csv('stemming.csv', index=False)

from wordcloud import WordCloud
import matplotlib.pyplot as plt

wc = WordCloud(background_color="white", max_words=2000, width=800, height=400)
wc.generate(' '.join(df['narasistem']))


plt.figure(figsize=(12, 6))
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.savefig("wc.png")
plt.show()